### ISSUE TITLE
Google Markers Deprecation

### ISSUE THREAD

**Issue by ragnarkurm** [margaridafp/google-maps-current-location#19]
# The problem

On the JS console there is a following warning:

> As of February 21st, 2024, google.maps.Marker is deprecated. Please use google.maps.marker.AdvancedMarkerElement instead. At this time, google.maps.Marker is not scheduled to be discontinued, but google.maps.marker.AdvancedMarkerElement is recommended over google.maps.Marker. While google.maps.Marker will continue to receive bug fixes for any major regressions, existing bugs in google.maps.Marker will not be addressed. At least 12 months notice will be given before support is discontinued. Please see https://developers.google.com/maps/deprecations for additional details and https://developers.google.com/maps/documentation/javascript/advanced-markers/migration for the migration guide.

# The cause

Google Maps Marker library is deprecated.

# The Goal

The warning is gone.

# The Solution

Upgrade from `google.maps.Marker` to `google.maps.marker.AdvancedMarkerElement`.

**Comment by belong-events** [comment]
The instructions are here:
https://developers.google.com/maps/documentation/javascript/advanced-markers/migration

**Comment by margaridafp** [comment]
Thanks for opening this! I will try to check this as soon as possible. 
If you already know how to migrate this, feel free to open a PR.

**Comment by margaridafp** [comment]
This issue should be fixed in the latest release `0.3.0`. 
Feel free to open any issues you might find. Thank you :)
